use comrak::html::ChildRendering;
use comrak::nodes::NodeValue;
use comrak::*;
use std::fmt::Write;

// Custom formatter for blog post markdown
// Generated by Claude code based on original index.html styling

create_formatter!(BlogFormatter, {
    // --- Block elements ---

    NodeValue::Heading(ref h) => |context, entering| {
        if entering {
            let classes = match h.level {
                1 => "text-2xl font-semibold tracking-tight text-mauve-50 mb-4 mt-8",
                2 => "text-xl font-semibold text-mauve-50 mb-3 mt-6",
                3 => "text-lg font-medium text-mauve-100 mb-2 mt-5",
                _ => "text-base font-medium text-mauve-100 mb-2 mt-4",
            };
            write!(context, r#"<h{} class="{}">"#, h.level, classes)?;
        } else {
            write!(context, "</h{}>", h.level)?;
        }
    },

    NodeValue::Paragraph => |context, node, entering| {
        // Don't wrap images in <p> tags — let them stand alone
        let dominated_by_image = node.children().all(|c|
            matches!(c.data.borrow().value, NodeValue::Image(_) | NodeValue::SoftBreak)
        );
        if dominated_by_image { return Ok(ChildRendering::HTML); }

        if entering {
            context.write_str(r#"<p class="text-sm leading-relaxed text-mauve-400 mb-4">"#)?;
        } else {
            context.write_str("</p>")?;
        }
    },

    NodeValue::BlockQuote => |context, entering| {
        if entering {
            context.write_str(
                r#"<blockquote class="border-l-2 border-violet-500/50 pl-4 my-4 text-sm text-mauve-500 italic">"#
            )?;
        } else {
            context.write_str("</blockquote>")?;
        }
    },

    NodeValue::List(ref nl) => |context, entering| {
        if entering {
            let base = "text-sm text-mauve-400 mb-4 ml-4 space-y-1";
            match nl.list_type {
                comrak::nodes::ListType::Bullet =>
                    write!(context, r#"<ul class="list-disc {base}">"#)?,
                comrak::nodes::ListType::Ordered =>
                    write!(context, r#"<ol class="list-decimal {base}">"#)?,
            };
        } else {
            if nl.list_type == comrak::nodes::ListType::Bullet {
                context.write_str("</ul>")?;
            } else {
                context.write_str("</ol>")?;
            }
        }
    },

    NodeValue::Item(_) => |context, entering| {
        context.write_str(if entering { "<li>" } else { "</li>" })?;
    },

    NodeValue::CodeBlock(ref cb) => |context| {
        context.write_str(
            r#"<pre class="rounded-lg border border-mauve-800 bg-mauve-950 p-4 my-4 overflow-x-auto"><code class="font-mono text-sm text-mauve-200">"#
        )?;
        comrak::html::escape(context, &cb.literal)?;
        context.write_str("</code></pre>")?;
    },

    // --- Inline elements ---

NodeValue::Link(ref nl) => |context, entering| {
    if entering {
        context.write_str(r#"<a href=""#)?;
        comrak::html::escape_href(context, &nl.url, false)?;
        context.write_str(r#"" class="text-violet-400 transition-colors hover:text-violet-300">"#)?;
    } else {
        context.write_str("</a>")?;
    }
},

    NodeValue::Emph => |context, entering| {
        context.write_str(if entering {
            r#"<em class="text-mauve-300">"#
        } else {
            "</em>"
        })?;
    },

    NodeValue::Strong => |context, entering| {
        context.write_str(if entering {
            r#"<strong class="font-semibold text-mauve-100">"#
        } else {
            "</strong>"
        })?;
    },

    NodeValue::Code(ref c) => |context| {
        context.write_str(
            r#"<code class="font-mono text-sm rounded bg-mauve-800/50 px-1.5 py-0.5 text-violet-400">"#
        )?;
        comrak::html::escape(context, &c.literal)?;
        context.write_str("</code>")?;
    },

    NodeValue::ThematicBreak => |context| {
        context.write_str(r#"<hr class="border-mauve-800 my-8" />"#)?;
    },
});
