package blog

import (
	"bytes"
	"fmt"
	"html"

	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/renderer"
	"github.com/yuin/goldmark/util"
)

// Custom formatter for goldmark
// Auto-magically generated by Claude code

type blogRenderer struct{}

func NewBlogRenderer() renderer.NodeRenderer {
	return &blogRenderer{}
}

func (r *blogRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(ast.KindHeading, r.renderHeading)
	reg.Register(ast.KindParagraph, r.renderParagraph)
	reg.Register(ast.KindBlockquote, r.renderBlockquote)
	reg.Register(ast.KindList, r.renderList)
	reg.Register(ast.KindListItem, r.renderListItem)
	reg.Register(ast.KindFencedCodeBlock, r.renderCodeBlock)
	reg.Register(ast.KindLink, r.renderLink)
	reg.Register(ast.KindEmphasis, r.renderEmphasis)
	reg.Register(ast.KindCodeSpan, r.renderCodeSpan)
	reg.Register(ast.KindThematicBreak, r.renderThematicBreak)
}

func (r *blogRenderer) renderHeading(w util.BufWriter, _ []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	n := node.(*ast.Heading)
	classes := map[int]string{
		1: "text-2xl font-semibold tracking-tight text-mauve-50 mb-4 mt-8",
		2: "text-xl font-semibold text-mauve-50 mb-3 mt-6",
		3: "text-lg font-medium text-mauve-100 mb-2 mt-5",
	}
	cls, ok := classes[n.Level]
	if !ok {
		cls = "text-base font-medium text-mauve-100 mb-2 mt-4"
	}
	if entering {
		fmt.Fprintf(w, `<h%d class="%s">`, n.Level, cls)
	} else {
		fmt.Fprintf(w, `</h%d>`, n.Level)
	}
	return ast.WalkContinue, nil
}

// dominatedByImage mirrors format.rs: don't wrap standalone images in <p>
func dominatedByImage(node ast.Node) bool {
	for c := node.FirstChild(); c != nil; c = c.NextSibling() {
		if c.Kind() != ast.KindImage {
			return false
		}
	}
	return true
}

func (r *blogRenderer) renderParagraph(w util.BufWriter, _ []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if dominatedByImage(node) {
		return ast.WalkContinue, nil
	}
	if entering {
		w.WriteString(`<p class="text-sm leading-relaxed text-mauve-400 mb-4">`)
	} else {
		w.WriteString("</p>")
	}
	return ast.WalkContinue, nil
}

func (r *blogRenderer) renderBlockquote(w util.BufWriter, _ []byte, _ ast.Node, entering bool) (ast.WalkStatus, error) {
	if entering {
		w.WriteString(`<blockquote class="border-l-2 border-violet-500/50 pl-4 my-4 text-sm text-mauve-500 italic">`)
	} else {
		w.WriteString("</blockquote>")
	}
	return ast.WalkContinue, nil
}

func (r *blogRenderer) renderList(w util.BufWriter, _ []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	n := node.(*ast.List)
	base := "text-sm text-mauve-400 mb-4 ml-4 space-y-1"
	if entering {
		if n.IsOrdered() {
			fmt.Fprintf(w, `<ol class="list-decimal %s">`, base)
		} else {
			fmt.Fprintf(w, `<ul class="list-disc %s">`, base)
		}
	} else {
		if n.IsOrdered() {
			w.WriteString("</ol>")
		} else {
			w.WriteString("</ul>")
		}
	}
	return ast.WalkContinue, nil
}

func (r *blogRenderer) renderListItem(w util.BufWriter, _ []byte, _ ast.Node, entering bool) (ast.WalkStatus, error) {
	if entering {
		w.WriteString("<li>")
	} else {
		w.WriteString("</li>")
	}
	return ast.WalkContinue, nil
}

func (r *blogRenderer) renderCodeBlock(w util.BufWriter, source []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}
	n := node.(*ast.FencedCodeBlock)
	w.WriteString(`<pre class="rounded-lg border border-mauve-800 bg-mauve-950 p-4 my-4 overflow-x-auto"><code class="font-mono text-sm text-mauve-200">`)
	lines := n.Lines()
	for i := 0; i < lines.Len(); i++ {
		line := lines.At(i)
		w.Write(util.EscapeHTML(line.Value(source)))
	}
	w.WriteString("</code></pre>")
	return ast.WalkSkipChildren, nil
}

func (r *blogRenderer) renderLink(w util.BufWriter, _ []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	n := node.(*ast.Link)
	if entering {
		fmt.Fprintf(w, `<a href="%s" class="text-violet-400 transition-colors hover:text-violet-300">`, html.EscapeString(string(n.Destination)))
	} else {
		w.WriteString("</a>")
	}
	return ast.WalkContinue, nil
}

func (r *blogRenderer) renderEmphasis(w util.BufWriter, _ []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	n := node.(*ast.Emphasis)
	if n.Level == 1 {
		if entering {
			w.WriteString(`<em class="text-mauve-300">`)
		} else {
			w.WriteString("</em>")
		}
	} else {
		if entering {
			w.WriteString(`<strong class="font-semibold text-mauve-100">`)
		} else {
			w.WriteString("</strong>")
		}
	}
	return ast.WalkContinue, nil
}

func (r *blogRenderer) renderCodeSpan(w util.BufWriter, source []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}
	w.WriteString(`<code class="font-mono text-sm rounded bg-mauve-800/50 px-1.5 py-0.5 text-violet-400">`)
	for c := node.FirstChild(); c != nil; c = c.NextSibling() {
		segment := c.(*ast.Text).Segment
		w.Write(util.EscapeHTML(bytes.TrimRight(segment.Value(source), "\n")))
	}
	w.WriteString("</code>")
	return ast.WalkSkipChildren, nil
}

func (r *blogRenderer) renderThematicBreak(w util.BufWriter, _ []byte, _ ast.Node, _ bool) (ast.WalkStatus, error) {
	w.WriteString(`<hr class="border-mauve-800 my-8" />`)
	return ast.WalkContinue, nil
}
